FROM node:latest

RUN npm -v
RUN node -v

RUN npm install -g nodemon

# Bundle APP files
WORKDIR /app

#handle package installation
COPY package*.json /app/
ENV NPM_CONFIG_LOGLEVEL verbose
#RUN npm install


#copy project files
COPY . .

EXPOSE 8080
